### ISSUE TITLE
`No module named 'keras.src.engine'` when importing urduhack

### ISSUE THREAD

**Issue by avidale** [urduhack/urduhack#153]
## How to reproduce the behaviour

When I run
```Python
import urduhack
```

I get the error `ModuleNotFoundError: No module named 'keras.src.engine'`, which is in turn triggered by the line `from tf2crf import CRF`. 

<details><summary>full stack trace</summary>
<p>

```
2024-06-19 16:22:25.065066: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-19 16:22:25.069047: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-19 16:22:25.121970: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-19 16:22:26.683978: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning:

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP).

For more information see: https://github.com/tensorflow/addons/issues/2807

  warnings.warn(
/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.13.0 and strictly below 2.16.0 (nightly versions are not supported).
 The versions of TensorFlow you are currently using is 2.16.1 and is not supported.
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version.
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/urduhack/__init__.py", line 6, in <module>
    from .pipeline import Pipeline
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/urduhack/pipeline/__init__.py", line 4, in <module>
    from .core import Pipeline
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/urduhack/pipeline/core.py", line 7, in <module>
    from .parsers.ner import NerParser
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/urduhack/pipeline/parsers/ner.py", line 4, in <module>
    from urduhack.models.ner import predict_ner
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/urduhack/models/ner/__init__.py", line 4, in <module>
    from .predict import predict_ner
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/urduhack/models/ner/predict.py", line 11, in <module>
    from urduhack.models.ner.model import _bi_lstm_crf_model
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/urduhack/models/ner/model.py", line 5, in <module>
    from tf2crf import CRF
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/tf2crf/__init__.py", line 2, in <module>
    from .crf import CRF
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/tf2crf/crf.py", line 2, in <module>
    import tensorflow_addons as tfa
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/tensorflow_addons/__init__.py", line 23, in <module>
    from tensorflow_addons import activations
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/tensorflow_addons/activations/__init__.py", line 17, in <module>
    from tensorflow_addons.activations.gelu import gelu
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/tensorflow_addons/activations/gelu.py", line 19, in <module>
    from tensorflow_addons.utils.types import TensorLike
  File "/private/home/daviddale/.conda/envs/meres1/lib/python3.10/site-packages/tensorflow_addons/utils/types.py", line 29, in <module>
    from keras.src.engine import keras_tensor
ModuleNotFoundError: No module named 'keras.src.engine'
``` 

</p>
</details> 

This is very frustrating, especially given that I need only rule-based functionality of this package, and I don't need the tensorflow models at all.

Is it possible to make the dependencies on `tf2crf` and `tensorflow` optional, and try importing them only if the user really needs  the neural models?

## Your Environment
* Operating System: Ubuntu
* Python Version Used: 3.10.13
* Urduhack Version Used: 1.1.1
* Environment Information: tensorflow==2.16.1, tf2crf==0.1.33.

**Comment by sharjeel103** [comment]
Have you got any solution?

**Comment by avidale** [comment]
No, I just copy-pasted the code I needed directly into my project without installing the whole urduhack package.

**Comment by ahsanalidev** [comment]
I am facing the same problem although I have installed urduhack

**Comment by MARafey** [comment]
@ahsanalidev and @avidale This is a python version issue as urduhack only supports till 3.8
