### ISSUE TITLE
word_tokenizer: Index out of bound error 

### ISSUE THREAD

**Issue by sami-haq99** [urduhack/urduhack#77]
I am tokenizing urdu data around 5k lines, it works well for 500-800 lines but when I run it over whole file it is generating index out of bound error and output file contains only 150 tokenized lines. 
P.S: I have already tokenized this file successfully using indic and nltk tokenizer. 
Error: 
Traceback (most recent call last):
  File "urduhack-tok.py", line 29, in <module>
    tokLine=word_tokenizer(sentence)
  File "/home/buraq/.virtualenvs/urduhack/lib/python3.6/site-packages/urduhack/tokenization/tokenizer.py", line 35, in word_tokenizer
    return predict(sentence, MODEL_PATH, VOCAB_PATH)
  File "/home/buraq/.virtualenvs/urduhack/lib/python3.6/site-packages/urduhack/tokenization/keras_tokenizer.py", line 119, in predict
    inp_, _ = preprocess_sentences(sentences, max_len, char2idx)
  File "/home/buraq/.virtualenvs/urduhack/lib/python3.6/site-packages/urduhack/tokenization/keras_tokenizer.py", line 55, in preprocess_sentences
    input_[i, char_index] = char2idx[letter]
IndexError: index 256 is out of bounds for axi

**Comment by muhammadfahid51** [comment]
As of now our tokenizer supports string length less than 256 characters so put an if condition before tokenizing a line/string, 
if len(line) <= 256 and it will work.
